"""Optional Stripe SDK integration and governed refund operations."""

from typing import TYPE_CHECKING

from ._operation import (
    StripeActionRepository,
    StripeActionSettings,
    StripePreparationError,
    StripeReservationStatus,
)
from .actions import RefundPreparationError, StripeActions, StripeRefunds
from .billing_testing import (
    BillingAuthorization,
    CreditGateway,
    InvoiceRepository,
    StripeBillingScenario,
    SubscriptionGateway,
    SubscriptionRepository,
    stripe_billing_scenario,
)
from .composition import RefundConfig, StripeServices, from_services
from .conformance import (
    StripeHostActionGroup,
    StripeHostCapabilities,
    StripeHostCloseStatus,
    StripeHostConformanceDescriptor,
    StripeHostConformanceDriver,
    StripeHostConformanceError,
    StripeHostConformanceReport,
    StripeHostExerciseAdapter,
    StripeHostExerciseDescriptor,
    StripeHostExerciseIntent,
    StripeHostExerciseReport,
    StripeHostIntentObservation,
    StripeHostIntentPhase,
    StripeHostNormalWriteCheckpoint,
    StripeHostNormalWriteStatus,
    StripeHostRememberStatus,
    StripeHostReserveStatus,
    StripeHostScenario,
    StripeHostScenarioDisposition,
    StripeHostScenarioResult,
    assert_stripe_host_conforms,
    assert_stripe_host_exercise,
    collect_stripe_host_attestation,
)
from .credit_notes import (
    CreditDisposition,
    CreditNoteCalculatedLine,
    CreditNoteCalculation,
    CreditNoteConfig,
    CreditNoteDraft,
    CreditNoteHost,
    CreditNoteInvoice,
    CreditNoteLine,
    CreditNoteLineRequest,
    CreditNoteLookup,
    CreditNoteObservation,
    CreditNoteOutcome,
    CreditNotePage,
    CreditNotePolicy,
    CreditNotePreview,
    CreditNoteRepository,
    CreditNoteRequest,
    CreditNoteSnapshot,
    CreditNoteTax,
    CustomerCreditObservation,
    InvoiceLineBinding,
    InvoiceObservation,
    StripeCreditNoteGateway,
    StripeCreditNotes,
)
from .gateway import (
    CORRELATION_KEY,
    ChargeObservation,
    RefundIntent,
    RefundObservation,
    RefundOutcome,
    RefundPage,
    RefundStatus,
    RefundWebhook,
    StripeAccount,
    StripeAccountId,
    StripeBoundaryError,
    StripeChargeId,
    StripeRefundConnector,
    StripeRefundGateway,
    StripeRefundId,
    verify_refund_webhook,
)
from .models import (
    RefundPayment,
    RefundPolicy,
    RefundPreview,
    RefundRequest,
    RefundReservationStatus,
    RefundSnapshot,
    StripeRefundSettings,
)
from .ports import RefundHost, RefundRepository
from .postgres import (
    PostgresStripeLedger,
    StripeLedgerEntry,
    StripeLedgerPhase,
    StripeLedgerReservationStatus,
    StripePostgresConnection,
    StripePostgresConnectionSource,
    StripePostgresHostError,
    stripe_resource_lock_reference,
)
from .postgres_migrations import (
    StripePostgresMigration,
    migrate_stripe_postgres,
    render_stripe_postgres_migration,
    stripe_postgres_migration,
)
from .recovery import (
    StripeCaseAcknowledgement,
    StripeEffectObservation,
    StripeObservedOutcome,
    StripeRecoveryCase,
)
from .subscriptions import (
    StripeSubscriptionGateway,
    StripeSubscriptions,
    SubscriptionBinding,
    SubscriptionCancellationConfig,
    SubscriptionCancellationHost,
    SubscriptionCancellationOutcome,
    SubscriptionCancellationPolicy,
    SubscriptionCancellationPreview,
    SubscriptionCancellationRepository,
    SubscriptionCancellationRequest,
    SubscriptionCancellationSnapshot,
    SubscriptionObservation,
    SubscriptionOperation,
)
from .testing import (
    StripeRefundScenario,
    StripeScenarioAuthorization,
    StripeScenarioGateway,
    StripeScenarioRepository,
    stripe_refund_scenario,
)

if TYPE_CHECKING:
    from .billing_gateway import StripeCreditNoteSDKGateway as StripeCreditNoteSDKGateway
    from .billing_gateway import (
        StripeSubscriptionSDKGateway as StripeSubscriptionSDKGateway,
    )
    from .sdk_gateway import StripeSDKGateway as StripeSDKGateway

__all__ = [
    "CORRELATION_KEY",
    "ChargeObservation",
    "RefundHost",
    "RefundConfig",
    "RefundIntent",
    "RefundObservation",
    "RefundOutcome",
    "RefundPage",
    "RefundPayment",
    "RefundPolicy",
    "RefundPreparationError",
    "RefundPreview",
    "RefundRepository",
    "RefundRequest",
    "RefundReservationStatus",
    "RefundSnapshot",
    "RefundStatus",
    "RefundWebhook",
    "PostgresStripeLedger",
    "StripeAccount",
    "StripeAccountId",
    "StripeActions",
    "StripeServices",
    "StripeScenarioAuthorization",
    "StripeScenarioGateway",
    "StripeScenarioRepository",
    "StripeLedgerEntry",
    "StripeLedgerPhase",
    "StripeLedgerReservationStatus",
    "StripePostgresConnection",
    "StripePostgresConnectionSource",
    "StripePostgresHostError",
    "StripePostgresMigration",
    "StripeHostActionGroup",
    "StripeHostCapabilities",
    "StripeHostConformanceDescriptor",
    "StripeHostConformanceDriver",
    "StripeHostConformanceError",
    "StripeHostConformanceReport",
    "StripeHostCloseStatus",
    "StripeHostExerciseAdapter",
    "StripeHostExerciseDescriptor",
    "StripeHostExerciseIntent",
    "StripeHostExerciseReport",
    "StripeHostIntentObservation",
    "StripeHostIntentPhase",
    "StripeHostNormalWriteStatus",
    "StripeHostNormalWriteCheckpoint",
    "StripeHostRememberStatus",
    "StripeHostReserveStatus",
    "StripeHostScenario",
    "StripeHostScenarioDisposition",
    "StripeHostScenarioResult",
    "StripeBoundaryError",
    "StripeCaseAcknowledgement",
    "StripeChargeId",
    "StripeRefundConnector",
    "StripeRefundGateway",
    "StripeRefundId",
    "StripeRefundSettings",
    "StripeRefundScenario",
    "StripeRefunds",
    "StripeSDKGateway",
    "verify_refund_webhook",
    "StripeActionRepository",
    "StripeActionSettings",
    "StripePreparationError",
    "StripeReservationStatus",
    "StripeCreditNoteSDKGateway",
    "StripeSubscriptionSDKGateway",
    "StripeSubscriptionGateway",
    "StripeSubscriptions",
    "SubscriptionBinding",
    "SubscriptionCancellationConfig",
    "SubscriptionCancellationHost",
    "SubscriptionCancellationOutcome",
    "SubscriptionCancellationPolicy",
    "SubscriptionCancellationPreview",
    "SubscriptionCancellationRepository",
    "SubscriptionCancellationRequest",
    "SubscriptionCancellationSnapshot",
    "SubscriptionObservation",
    "SubscriptionOperation",
    "CreditDisposition",
    "CreditNoteCalculatedLine",
    "CreditNoteCalculation",
    "CreditNoteConfig",
    "CreditNoteDraft",
    "CreditNoteHost",
    "CreditNoteInvoice",
    "CreditNoteLine",
    "CreditNoteLineRequest",
    "CreditNoteLookup",
    "CreditNoteObservation",
    "CreditNoteOutcome",
    "CreditNotePage",
    "CreditNotePolicy",
    "CreditNotePreview",
    "CreditNoteRepository",
    "CreditNoteRequest",
    "CreditNoteSnapshot",
    "CreditNoteTax",
    "CustomerCreditObservation",
    "InvoiceLineBinding",
    "InvoiceObservation",
    "StripeCreditNoteGateway",
    "StripeCreditNotes",
    "StripeEffectObservation",
    "StripeObservedOutcome",
    "StripeRecoveryCase",
    "BillingAuthorization",
    "CreditGateway",
    "InvoiceRepository",
    "StripeBillingScenario",
    "SubscriptionGateway",
    "SubscriptionRepository",
    "assert_stripe_host_conforms",
    "assert_stripe_host_exercise",
    "collect_stripe_host_attestation",
    "from_services",
    "migrate_stripe_postgres",
    "render_stripe_postgres_migration",
    "stripe_postgres_migration",
    "stripe_billing_scenario",
    "stripe_refund_scenario",
    "stripe_resource_lock_reference",
]


def __getattr__(name: str) -> object:
    if name == "StripeSDKGateway":
        from .sdk_gateway import StripeSDKGateway

        return StripeSDKGateway
    if name == "StripeSubscriptionSDKGateway":
        from .billing_gateway import StripeSubscriptionSDKGateway

        return StripeSubscriptionSDKGateway
    if name == "StripeCreditNoteSDKGateway":
        from .billing_gateway import StripeCreditNoteSDKGateway

        return StripeCreditNoteSDKGateway
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
