"""Evidence-only approval requirements.

These helpers evaluate already authenticated and host-authorized authority
evidence. They never decide whether an authority is currently permitted to act.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from typing import TYPE_CHECKING

from .authority import (
    AuthorityBinding,
    AuthorityDecision,
    AuthorityEvidence,
    authority_evidence_matches_binding,
)
from .registry import AuthorityEvaluation

if TYPE_CHECKING:
    from .models import ConfirmingAuthority


def _references(authorities: tuple[ConfirmingAuthority, ...]) -> tuple[str, ...]:
    return tuple(authority.reference for authority in authorities)


def _validate_authorities(authorities: tuple[ConfirmingAuthority, ...]) -> None:
    if not authorities:
        raise ValueError("at least one authority is required")
    references = _references(authorities)
    if len(set(references)) != len(references):
        raise ValueError("authorities must be distinct")


class ApprovalReasonCode(StrEnum):
    """Reason codes generated by the evidence-only approval requirements."""

    MORE_AUTHORITY_REQUIRED = "more_authority_required"


def _satisfied(
    *,
    required: int,
    authorities: tuple[ConfirmingAuthority, ...],
    binding: AuthorityBinding,
    evidence: tuple[AuthorityEvidence, ...],
) -> AuthorityEvaluation:
    allowed = set(_references(authorities))
    approving = {
        record.authority.reference
        for record in evidence
        if record.decision is AuthorityDecision.APPROVE
        and record.authority.reference in allowed
        and authority_evidence_matches_binding(record, binding=binding)
    }
    satisfied = len(approving) >= required
    return AuthorityEvaluation(
        satisfied=satisfied,
        reason_code=None if satisfied else ApprovalReasonCode.MORE_AUTHORITY_REQUIRED.value,
    )


@dataclass(frozen=True)
class SingleApproval:
    """Require one specific authority after the host authorizes the decision."""

    authority: ConfirmingAuthority

    async def evaluate(
        self,
        *,
        binding: AuthorityBinding,
        evidence: tuple[AuthorityEvidence, ...],
    ) -> AuthorityEvaluation:
        return _satisfied(
            required=1,
            authorities=(self.authority,),
            binding=binding,
            evidence=evidence,
        )


@dataclass(frozen=True)
class AnyApproval:
    """Require one distinct authority from a declared set."""

    authorities: tuple[ConfirmingAuthority, ...]

    def __post_init__(self) -> None:
        _validate_authorities(self.authorities)

    async def evaluate(
        self,
        *,
        binding: AuthorityBinding,
        evidence: tuple[AuthorityEvidence, ...],
    ) -> AuthorityEvaluation:
        return _satisfied(
            required=1,
            authorities=self.authorities,
            binding=binding,
            evidence=evidence,
        )


@dataclass(frozen=True)
class MOfNApprovals:
    """Require approvals from a distinct M-of-N set of authorities."""

    required: int
    authorities: tuple[ConfirmingAuthority, ...]

    def __post_init__(self) -> None:
        _validate_authorities(self.authorities)
        if not 1 <= self.required <= len(self.authorities):
            raise ValueError("required must be between one and the authority count")

    async def evaluate(
        self,
        *,
        binding: AuthorityBinding,
        evidence: tuple[AuthorityEvidence, ...],
    ) -> AuthorityEvaluation:
        return _satisfied(
            required=self.required,
            authorities=self.authorities,
            binding=binding,
            evidence=evidence,
        )
